/**
 * Generates public/__forms.html — the static declaration Netlify needs to detect the forms
 * (the real forms render client-side). Field lists come from content/onboarding.ts.
 */
import fs from "node:fs";
import path from "node:path";
import { ONBOARDING, ONBOARDING_META, APPLICATION_FIELDS, FORM_NAMES } from "../content/onboarding.ts";

const root = path.resolve(import.meta.dirname, "..");
const input = (name: string, type = "text") => `    <input type="${type}" name="${name}" />`;
const onb = [...ONBOARDING.flatMap((s) => s.fields.map((f) => (f.type === "textarea" ? `    <textarea name="${f.name}"></textarea>` : input(f.name, f.type === "file" ? "file" : f.type === "checkbox" ? "checkbox" : "text")))), ...ONBOARDING_META.map((m) => (m === "summary" ? `    <textarea name="summary"></textarea>` : input(m, "hidden")))];
const app = APPLICATION_FIELDS.map((m) => (m === "summary" || m === "data_json" ? `    <textarea name="${m}"></textarea>` : input(m, "hidden")));

const html = `<!doctype html>
<html lang="en"><head><meta charset="utf-8" /><meta name="robots" content="noindex" /><title>Forms</title></head>
<body>
  <!-- Generated by scripts/build-forms.mts — do not edit. Netlify Forms detection only; real forms render client-side. -->
  <form name="${FORM_NAMES.application}" data-netlify="true" netlify-honeypot="bot-field" hidden>
    <input name="bot-field" />
${app.join("\n")}
  </form>
  <form name="${FORM_NAMES.onboarding}" data-netlify="true" netlify-honeypot="bot-field" enctype="multipart/form-data" hidden>
    <input name="bot-field" />
${onb.join("\n")}
  </form>
</body></html>
`;
fs.writeFileSync(path.join(root, "public/__forms.html"), html);
console.log(`✓ Forms: ${FORM_NAMES.application}, ${FORM_NAMES.onboarding}`);
