// Builds the Concordia Soccer · European Pathway logo system.
// Wordmark geometry follows the existing Concordia Sports Agency wordmark (stadium C,
// round O, descending N stem, rounded R/D bowls, open A); the first O becomes the
// globe + route mark. The descriptor is converted to outlines so the SVGs are font-free.
import fs from "node:fs";
import opentype from "opentype.js";

const S = 17; // stroke weight
const h = S / 2;
const ROUTE = "#FFD23F";

// Letter strokes on a 100-unit cap height. N's stem descends to underline the descriptor.
const letters = [
  `M95 ${h}H50A${50 - h} ${50 - h} 0 0 0 50 ${100 - h}H95`, // C
  null, // globe O (drawn separately)
  `M${233 + h} 140V0M${233 + h} ${h}L${310 - h} ${100 - h}M${310 - h} 100V0`, // N
  `M420 ${h}H375A${50 - h} ${50 - h} 0 0 0 375 ${100 - h}H420`, // C
  `M${475 + 50 - h} 50A${50 - h} ${50 - h} 0 1 1 ${475 + 50 - h} 49.99`, // O
  `M${545 + h} 100V${h}H595A${21.5} ${21.5} 0 0 1 595 ${51.5}H${545 + h}M590 51.5L620 100`, // R
  `M${640 + h} ${h}V${100 - h}H683A${41.5} ${41.5} 0 0 0 683 ${h}Z`, // D
  `M${752 + h} 0V100`, // I
  `M782 100L830 6L878 100`, // A
].filter(Boolean);

const globe = (stroke, route, id = "g") => `
  <defs><clipPath id="${id}"><circle cx="160" cy="50" r="33.5"/></clipPath></defs>
  <g fill="none" stroke-linecap="butt">
    <path d="M199 35.8A41.5 41.5 0 1 1 177.5 12.4" stroke="${stroke}" stroke-width="${S}"/>
    <g clip-path="url(#${id})" stroke="${stroke}" stroke-width="4">
      <ellipse cx="160" cy="50" rx="14" ry="34"/>
      <path d="M160 14V86"/>
      <path d="M124 36Q160 46 196 36M122 62Q160 72 198 62"/>
    </g>
    <path d="M129 83C151 73 174 52 191 21" stroke="${stroke === route ? stroke : "#0D1B3600"}" stroke-width="0"/>
    <path d="M129 83C151 73 174 52 191 21" stroke="${route}" stroke-width="7"/>
    <path d="M200 5L185 17.5L198.5 25Z" fill="${route}" stroke="none"/>
  </g>`;

const font600 = opentype.parse(fs.readFileSync("node_modules/@fontsource/public-sans/files/public-sans-latin-700-normal.woff").buffer);
const font400 = opentype.parse(fs.readFileSync("node_modules/@fontsource/public-sans/files/public-sans-latin-400-normal.woff").buffer);

function tracked(font, text, size, tracking) {
  let x = 0;
  const glyphs = [];
  for (const ch of text) {
    const g = font.charToGlyph(ch);
    glyphs.push({ g, x });
    x += (g.advanceWidth / font.unitsPerEm) * size + tracking;
  }
  return { glyphs, width: x - tracking };
}
function toPath(font, run, x0, y, size) {
  return run.glyphs.map(({ g, x }) => g.getPath(x0 + x, y, size).toPathData(2)).join("");
}

// Descriptor: SOCCER (light, secondary) · EUROPEAN PATHWAY (bold, primary)
const size = 22, base = 133, right = 878;
const ep = tracked(font600, "EUROPEAN PATHWAY", size, 10.5);
const dot = tracked(font600, "·", size, 0);
const so = tracked(font400, "SOCCER", size, 10.5);
const epX = right - ep.width;
const dotX = epX - 16 - dot.width;
const soX = dotX - 16 - so.width;
const soccerD = toPath(font400, so, soX, base, size);
const dotD = toPath(font600, dot, dotX, base, size);
const epD = toPath(font600, ep, epX, base, size);

const W = 888, H = 148;
function lockup({ ink, route, soccer, bg }) {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" role="img" aria-label="Concordia Soccer · European Pathway">${bg ? `<rect width="${W}" height="${H}" fill="${bg}"/>` : ""}
  <g fill="none" stroke="${ink}" stroke-width="${S}">${letters.map((d) => `<path d="${d}"/>`).join("")}</g>${globe(ink, route)}
  <path d="${soccerD}" fill="${soccer}"/><path d="${dotD}" fill="${soccer}"/><path d="${epD}" fill="${ink}"/>
</svg>\n`;
}
function mark({ ink, route, bg, pad = 0 }) {
  const vb = `${110 - pad} ${0 - pad} ${100 + pad * 2} ${100 + pad * 2}`;
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${vb}" role="img" aria-label="Concordia Soccer">${bg ? `<rect x="${110 - pad}" y="${-pad}" width="${100 + pad * 2}" height="${100 + pad * 2}" rx="${pad ? 18 : 0}" fill="${bg}"/>` : ""}${globe(ink, route)}</svg>\n`;
}

const out = "public/brand";
fs.writeFileSync(`${out}/concordia-pathway-primary.svg`, lockup({ ink: "#0D1B36", route: "#E0A800", soccer: "#5E6878" }));
fs.writeFileSync(`${out}/concordia-pathway-reversed.svg`, lockup({ ink: "#FFFFFF", route: ROUTE, soccer: "#AEB6C4" }));
fs.writeFileSync(`${out}/concordia-pathway-black.svg`, lockup({ ink: "#000000", route: "#000000", soccer: "#000000" }));
fs.writeFileSync(`${out}/concordia-pathway-compact.svg`, mark({ ink: "#FFFFFF", route: ROUTE }));
fs.writeFileSync(`${out}/concordia-pathway-favicon.svg`, mark({ ink: "#FFFFFF", route: ROUTE, bg: "#0D1B36", pad: 14 }));
fs.writeFileSync("app/icon.svg", mark({ ink: "#FFFFFF", route: ROUTE, bg: "#0D1B36", pad: 14 }));

// Geometry for the React <Logo/> component (single source of truth).
fs.writeFileSync("components/brand/logo-geometry.ts",
`// Generated by scripts/build-logo.mjs — do not edit by hand.
export const LOGO_VIEWBOX = "0 0 ${W} ${H}";
export const STROKE = ${S};
export const LETTERS: string[] = ${JSON.stringify(letters)};
export const SOCCER_D = ${JSON.stringify(soccerD + dotD)};
export const PATHWAY_D = ${JSON.stringify(epD)};
`);
console.log("logo built", { soX: Math.round(soX), epX: Math.round(epX) });
