import { pending, type Evidence } from "@/lib/evidence";

export interface FaqItem { q: string; a: string; category: "assessment" | "programmes" | "representation" | "parents" | "practical"; home?: boolean; evidence?: Evidence }

export const faq: FaqItem[] = [
  { q: "Do you guarantee a trial or contract?", a: "No. Nobody honest can. We assess, advise and plan. We don’t arrange trials or contact clubs as part of European Pathway.", category: "assessment", home: true },
  { q: "Will you contact clubs for me?", a: "Not as part of European Pathway. Club contact on a player’s behalf happens only under formal representation by Concordia Sports Agency, which is separate and selective.", category: "representation", home: true },
  { q: "What if you tell me I’m not ready?", a: "Then you’ll know why, what to work on, and what a realistic next step looks like. That answer is part of what you pay for.", category: "assessment", home: true },
  { q: "Does buying European Pathway make representation more likely?", a: "No. Representation can’t be bought, and no Pathway service changes a player’s right, entitlement or chance of being represented.", category: "representation", home: true },
  { q: "My child is under 18. How does this work?", a: "A parent or guardian applies, pays and is welcome on every call. Under-16s receive guidance only — no assessment is sold.", category: "parents", home: true },
  { q: "Who reviews my match?", a: "A qualified member of our team analyses your full match, and every assessment follows Concordia’s professional assessment framework and receives senior review.", category: "assessment", home: true, evidence: pending("E13", "Final sign-off wording") },
  { q: "Is the application really free?", a: "Yes. We review every application before accepting payment. If an assessment is right for you, you’ll be invited to pay $249 online.", category: "assessment" },
  { q: "What does “accepted” mean?", a: "Being accepted means accepted for a Pathway Assessment — not for representation, by the Agency or by any club. It doesn’t mean Concordia has agreed to represent you, that you’ve signed with the Agency, that any club is interested, or that a trial, contract or transfer is guaranteed.", category: "assessment" },
  { q: "What footage do I need?", a: "Video helps — full, unedited matches most of all, plus highlights if you have them. If you don’t have a full match, a highlight video or a Transfermarkt profile, tell us: none of these is an automatic barrier. After you submit your materials, our team confirms whether we have what’s reasonably required for your assessment.", category: "assessment" },
  { q: "Can I play in Europe without an EU passport?", a: "Sometimes — it depends on the country and the division. Your assessment explains what your passport(s) mean for the markets that fit your profile.", category: "assessment" },
  { q: "I’m still in college. Does this affect my eligibility?", a: "The assessment is career advisory and involves no agency agreement. Check with your compliance office if you have eligibility questions.", category: "practical", evidence: pending("E35", "Wording to be confirmed with US counsel") },
  { q: "What happens after the assessment?", a: "You read the report and take the call. If European Pathway makes sense, we’ll explain why — $399/month, designed as a 6-month pathway, paid monthly. If it doesn’t, we’ll say so.", category: "programmes" },
  { q: "Is contract review included?", a: "Yes. In European Pathway your career team reviews offers and contracts with you and explains what they commit you to before you sign. Where formal legal advice is needed in a specific country, we’ll tell you.", category: "programmes" },
  { q: "Is European Pathway paid monthly?", a: "Yes — $399 per month. It’s designed as a 6-month European career pathway, paid monthly, so you never pay the six months upfront. Cancellation options are available; final subscription terms apply.", category: "programmes", home: true },
  { q: "What’s the refund policy?", a: "Assessment: full refund until we begin reviewing your materials. European Pathway: terms are set out in the Refund & Cancellation Policy.", category: "practical", evidence: pending("E24", "Approved refund policy text") },
  { q: "Who am I contracting with?", a: "Concordia Soccer · European Pathway services are provided by Concordia Sports Agency SIA (Reg. No. 40203574668), Rīga, Latvia. Buying a Pathway service does not create a football-agent representation agreement.", category: "practical" },
];
