import type { NextConfig } from "next";
import path from "node:path";

/**
 * Server deployment on Netlify (Next.js runtime): pages are still prerendered where possible, while
 * /api/* route handlers run as Netlify Functions (applications, email, Stripe checkout + webhook, admin).
 * The former static export (output: "export") could not securely host any of those, so it was retired.
 */
const nextConfig: NextConfig = {
  // Responsive WebP variants are pre-generated by scripts/build-images.mjs (widths must match WIDTHS there).
  images: { loader: "custom", loaderFile: "./lib/image-loader.ts", deviceSizes: [480, 828, 1280, 1920], imageSizes: [256] },
  poweredByHeader: false,
  // This app is isolated from the Agency app at the repository root.
  turbopack: { root: path.join(__dirname) },
  // Signed player links live in the URL: never send them onward as a Referer, never cache these pages or the API.
  async headers() {
    const priv = [{ key: "Referrer-Policy", value: "no-referrer" }, { key: "Cache-Control", value: "private, no-store" }, { key: "X-Robots-Tag", value: "noindex, nofollow" }];
    return ["/status", "/checkout/:path*", "/onboarding", "/admin/:path*", "/admin", "/api/:path*"].map((source) => ({ source, headers: priv }));
  },
  async redirects() {
    return [
      // Retired pages — permanent redirects so old links and indexed URLs never 404.
      { source: "/football-law", destination: "/european-pathway", permanent: true },
      { source: "/programmes", destination: "/european-pathway", permanent: true },
      { source: "/programmes/:slug*", destination: "/european-pathway", permanent: true },
      { source: "/checkout/cohort", destination: "/european-pathway", permanent: true },
      { source: "/checkout/window", destination: "/european-pathway", permanent: true },
      { source: "/checkout/two-window", destination: "/european-pathway", permanent: true },
      { source: "/checkout/elite", destination: "/european-pathway", permanent: true },
      { source: "/checkout/pathway-club", destination: "/european-pathway", permanent: true },
      { source: "/checkout/european-pathway", destination: "/european-pathway", permanent: true },
      { source: "/checkout/confirmation", destination: "/status", permanent: true },
      { source: "/assessment-status", destination: "/status", permanent: true },
      { source: "/apply/result", destination: "/apply", permanent: true },
      { source: "/review/emails", destination: "/admin", permanent: true },
      { source: "/about/marks-amosejevs", destination: "/about#team", permanent: true },
      { source: "/legal/safeguarding", destination: "/legal/minors", permanent: true },
    ];
  },
};

export default nextConfig;
