import type { NextConfig } from "next";
import path from "node:path";

// PREVIEW_EXPORT=1 produces a static export (out/) — used for the Netlify review deployment.
const isExport = process.env.PREVIEW_EXPORT === "1";

const nextConfig: NextConfig = {
  ...(isExport ? { output: "export" as const, trailingSlash: true } : {}),
  // Responsive WebP variants are pre-generated by scripts/build-images.mjs (widths must match WIDTHS there).
  images: { loader: "custom", loaderFile: "./lib/image-loader.ts", deviceSizes: [480, 828, 1280, 1920], imageSizes: [256] },
  poweredByHeader: false,
  // This app is isolated from the Agency app at the repository root.
  turbopack: { root: path.join(__dirname) },
};

export default nextConfig;
